title: "21 Ducks: Aylesbury United Supporters Trust"
description: "21st Century Ducks is the Aylesbury United Supporters Trust."

collections:
    videos:
        output: true
        permalink: /:collection/:name
    events:
        output: true
        permalink: /:collection/:name
