name: On Merge Build & Deploy

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    uses: ./.github/workflows/deploy.yml
